connection: 
  host: irc.freenode.net
  port: 6697
  secure: true
  status_command: ACC
  debug: false
login: 
  nickname: Aerotippy
  username: Aerotippy
  realname: node.js Aero tipping bot
  nickserv_password: password
channels: 
  - '#aerocoin'
log:
  file: cannatip.log
rpc:
  host: localhost
  port: 7142
  user: rpcuser
  pass: rpcpass
coin:
  withdrawal_fee: .1 
  min_withdraw: 1
  min_confirmations: 3
  min_tip: 1
  short_name: AERO
  full_name: Aerocoin
webadmin:
  enabled: true
  port: 8080
  users:
    admin: password
    secondadmin: password
commands:
  help:
    pm: true
    channel: false
  tip:
    pm: true
    channel: true 
  rain: 
    pm: true
    channel: true      
  balance:
    pm: true
    channel: false
  withdraw:
    pm: true
    channel: false
  address:
    pm: true
    channel: false
  terms:
    pm: true
    channel: false
  diff:
    pm: true
    channel: true
  networkhps:
    pm: true
    channel: true        
messages:
  error: 'Sorry %name%, something went wrong.'
  no_funds: "Sorry %name%, you don't have enough funds (you're %short%%short_name% short)"
  not_identified: '%name%: You need to be identified with NickServ to tip.'
  tipped: '%from% tipped %to% %amount%%short_name%! "/msg %nick% help" to claim.'
  balance: '%name% has %balance% %short_name%.'
  balance_unconfirmed: '%name% has %balance% %short_name% (unconfirmed: %unconfirmed% %short_name%)'
  deposit_address: '%name%, your deposit address is %address%'
  withdraw_too_small: 'Sorry %name%, you need to withdraw at least %min_withdraw%%short_name% (you have %balance%%short_name%)'
  invalid_address: 'Sorry %name%, the address you specified is invalid (%address%).'
  tip_too_small: 'Sorry %from%, your tip to %to% (%amount%%short_name%) is too small (min. %min_tip%%short_name%).'
  rain_too_small: 'Sorry %from%, your rain (%amount%%short_name%) is too small (min. %min_rain%%short_name%). Increase the value or decrease max wet users.' 
  tip_self: "Sorry %name%, you can't tip yourself!"
  invalid_amount: 'Sorry %name%, "%amount%" is not a correct amount.'
  rain: '%name% rained %amount%%short_name% upon %list%.' 
  withdraw_success: 
    - '%name%: %amount%%short_name% has been withdrawn from your account to %address%'
    - 'You have been charged %withdrawal_fee%%short_name% withdrawal fee.'
    - 'Transaction %transaction% completed.'
  help:
    - 'You can use following commands:'
    - '!balance - displays your current wallet balance'
    - '!address - displays %full_name% address where you can send your funds to the tip bot'
    - '!withdraw <%full_name% address> - withdraws your whole wallet balance to specified address (you will be charged %withdrawal_fee%%short_name% withdrawal fee)'
    - '!tip <nick> <amount> - sends the specified amount of %full_name% to the specified nickname'
    - '!rain <amount> [max] - splits amount coins between max users or the whole channel'
    - '!diff - displays the current network difficulty'
    - '!networkhps - displays the current network hashpersec'    
    - '!terms - displays terms and conditions for using %nick%'
  terms:
    - 'There are no fees to use %nick%, with the exception of %withdrawal_fee%%short_name% fee on withdrawals.'
    - 'Warning: This service is provided "as is" without warranty of any kind, either express or implied, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, non-infringement, error-free or uninterrupted service. You are using this service at your own risk; in addition, the coins in your account are only as secure as your IRC account is. Do not hold large sums of coins here; simply withdraw or tip others.'
  getdiff: 'Current Difficulty: %diff%'
  networkhps: 'Current Networkhps: %networkhps% Mh/s'
